#!/usr/bin/env ruby

require "runa"
require "thor"
require "fileutils"
require "os"

class RunaCli < Thor
  def self.exit_on_failure?
    true
  end

  desc "new NAME", "Create a new application"
  def new(name)
    if FileTest.exist?(name)
      raise Thor::Error, "ERROR: '#{File.absolute_path(name)}' already exists"
    end

    module_name = name.split("_").map { |e| e.capitalize }.join

    FileUtils.mkdir_p(name)
    Dir.chdir(name) do
      FileUtils.mkdir_p(RUNA_DIR)
      File.write("#{RUNA_DIR}/.gitkeep", "")
      FileUtils.mkdir_p(".bundle")
      File.write(".bundle/config", "---\nBUNDLE_PATH: \"vendor/bundle\"\n")
      FileUtils.mkdir_p("lib/#{name}")
      File.write("lib/#{name}.rb", "require \"#{name}/lib\"\n")
      File.write("lib/#{name}/lib.rb", "module #{module_name}\nend\n")
      File.write(".gitignore", "/vendor/\n/.runa/*\n!/.runa/.gitkeep\n")
      File.write("Gemfile", "# frozen_string_literal: true\n\nsource \"https://rubygems.org\"\n\n# gem \"rails\"\n")
      File.write("#{name}.rb", "require \"#{name}\"\n\nputs \"Hello, world!\"")
    end

    puts "Created '#{name}' application."
  end

  desc "gem_add", "Add gems"
  def gem_add(*gems)
    system("bundle add #{gems.join(" ")}")
    deploy_load_path_script
  end

  desc "install", "Install gems"
  def install
    system("bundle install")
    deploy_load_path_script
  end

  desc "run SCRIPT_FILE [ARGS]", "Run application with arguments"
  def run_command(script_name, *args)
    system("bundle exec ruby -Ilib #{script_name} #{args.join(" ")}")
  end
  map "run" => "run_command"

  desc "deploy", "Deploy scripts for production execution"
  def deploy
    root_dir = File.expand_path(".")
    deploy_script_name = File.basename(root_dir)
    deploy_load_path_script
    path = File.join(RUNA_DIR, deploy_script_name)
    path += ".bat" if OS.windows?
    File.write(path, deploy_script(root_dir))
    puts "Generate '#{path}'\n'#{path}' is the script to run. Copy it to any location and use it."
  end

  private

  RUNA_DIR = ".runa"

  def deploy_script(root_dir)
    lib_dir = File.join(root_dir, "lib")
    runa_dir = File.join(root_dir, RUNA_DIR)
    main_rb = File.join(root_dir, "main.rb")

    if OS.windows?
      lib_dir = lib_dir.tr("/", "\\")
      runa_dir = runa_dir.tr("/", "\\")
      main_rb = main_rb.tr("/", "\\")

      <<~EOS
        @ECHO OFF
        @ruby -I"#{lib_dir}" -I"#{runa_dir}" -rruna_load_path #{main_rb} %*
      EOS
    else
      <<~EOS
        #!/bin/sh
        ruby -I"#{lib_dir}" -I"#{runa_dir}" -rruna_load_path #{main_rb} $@
      EOS
    end
  end

  def deploy_load_path_script
    path = "#{RUNA_DIR}/runa_load_path.rb"
    File.write(path, load_path_script)
    puts "Generate '#{path}'"
  end

  def load_path_script
    str = `bundle exec ruby -e 'puts \$LOAD_PATH.grep(/vendor\\/bundle/)'`
    paths = str.split("\n").map { |e| "\"#{e}\"" }.join(",")
    "$LOAD_PATH.unshift(#{paths})\n"
  end
end

RunaCli.start(ARGV)
